version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo2021!
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDB:/data/db
    networks:
      - mongo-compose-network
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: desafioreact
      ME_CONFIG_BASICAUTH_PASSWORD: Mongo2021!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mongo2021!
    links:
      - mongodb:mongodb
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge